version: 2
updates:
  # Monitoramento de dependências npm/yarn
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"

  # Monitoramento de GitHub Actions Workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  # Monitoramento de Dockerfile
  - package-ecosystem: "docker"
    directory: "/infra/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      docker:
        patterns:
          - "*"
